<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GdTracker.Core\GdTracker.Core.csproj" />
    <ProjectReference Include="..\GdTracker.Data\GdTracker.Data.csproj" />
    <ProjectReference Include="..\GdTracker.GameSync\GdTracker.GameSync.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView" Version="2.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
